### ISSUE TITLE
[Feature Request] Substitute with register

### ISSUE THREAD

**Issue by luiz00martins** [gbprod/substitute.nvim#22]
I currently have the following setup in my `vim-subversive`:
```lua
map('x', 'py', '"0<plug>(SubversiveSubstitute)', {noremap = false})
map('x', 'Py', '"0<plug>(SubversiveSubstituteRange)', {noremap = false})
map('x', 'pd', '"1<plug>(SubversiveSubstitute)', {noremap = false})
map('x', 'Pd', '"1<plug>(SubversiveSubstituteRange)', {noremap = false})
map('x', 'p+', '"+<plug>(SubversiveSubstitute)', {noremap = false})
map('x', 'P+', '"+<plug>(SubversiveSubstituteRange)', {noremap = false})
```
So, for example, after visually selecting `some_text`:
 - `py` will replace `some_text` with `copied_text`
 - `pd` will replace `some_text` with `deleted_text`
 - `Pd5j` will replace every instance of `some_text` up to 5 lines down with `deleted_text`

It'd be nice if `substitute.nvim` could also interact with registers in this way (e.g. an option to specify a register that would be used in the substitution).

**Comment by gbprod** [comment]
Nice idea ! I can do something soon 😉

**Comment by gbprod** [comment]
Can you try using this branch : https://github.com/gbprod/substitute.nvim/pull/27 ?

This will only fix `SubversiveSubstitute` cases (I will work later for range):

```lua
vim.keymap.set('x', 'py', "lua require('substitute').operator({ register = '0' })",  { noremap = false})
```

**Comment by luiz00martins** [comment]
Just tested it, it's working perfectly!

**Comment by gbprod** [comment]
Next feature :)
Can you try using this branch : https://github.com/gbprod/substitute.nvim/pull/28 ?

This will introduce register management for `substitute.range`:

```lua
vim.keymap.set('x', 'Py', "lua require('substitute.range').operator({ register = '0' })",  { noremap = false })
```
Thanks :)

**Comment by luiz00martins** [comment]
Most of it seems to be working fine. 

However, the `+` register (`map('x', 'P+', '<cmd>lua require("substitute.range").operator({ register = "+" })<cr>')`) seems to be getting its contents from other registers (specifically, the last updated one), instead of the actual register:

 - If you delete something, it substitutes with the contents with register `1`, instead of register `+`
 - If you yank something, it substitutes with the contents with register `0`, instead of register `+`
 - If copy something to the clipboard from outside neovim, say "`new_text`", it substitutes with the previous register value, instead of the copied "`new_text`"

**Comment by gbprod** [comment]
What are your settings for `clipboard` ? (`:set clipboard?`)
And what are your settings for `substitute.nvim` ?

**Comment by luiz00martins** [comment]
In that case... it's not working! Just tested in all cases, and all of them yield the same output. They are pulling the last used register containing `some_text`, and outputting `:'[,']s/some_text//g`, independent of the value of `register` parameter.

I have no clipboard configs, all default.

These are my `substitute.nvim` settings:
```lua
require("substitute").setup({
	on_substitute = nil,
	yank_substituted_text = false,
	range = {
		prefix = "s",
		prompt_current_text = false,
		confirm = false,
	},
})
```

**Comment by gbprod** [comment]
Ok :sweat_smile: 
Can you test again ?

Thanks :)

**Comment by luiz00martins** [comment]
Working perfectly, thanks for the feature!

*Gonna leave it to you to close the issue when you merge to main*

**Comment by gbprod** [comment]
Thanks !
