### ISSUE TITLE
[Feature Request] Group substituted word

### ISSUE THREAD

**Issue by luiz00martins** [gbprod/substitute.nvim#23]
Currently, substituting `my_text` leaves you with `:'[,']s/my_text/|/g` (`|` being the cursor):

My suggestion, is to instead use `:'[,']s/\(my_text\)/|/g`, automatically capturing `my_text` in a group.

This would allow users to more quickly complete with the current text with `\1`. For example:

```
:'[,']s/\(my_text\)/\1_is_amesome/g
:'[,']s/\(my_text\)/this_is_\1/g
:'[,']s/\(my_text\)/this_is_\1_and_now_way_longer/g
```
which  result in
```
my_text_is_amesome
this_is_my_text
this_is_my_text_and_now_way_longer
```

---

This is an alternative to `yank_substituted_text`. However, I prefer it, because it doesn't clobber the yank register.

**Comment by gbprod** [comment]
I've tried to do something here : https://github.com/gbprod/substitute.nvim/pull/30

It's a really cool feature :)
