### ISSUE TITLE
[Bug] Ranged highlight only highlights the previously used range.

### ISSUE THREAD

**Issue by luiz00martins** [gbprod/substitute.nvim#25]
Here's an example. The first time the visual ranged substitution is used on `map`, all of the `map`s are correctly highlighted:
![normal](https://user-images.githubusercontent.com/43142209/169859450-b4857b44-9bd7-4900-9e73-cc3d3346a0ae.png)

Then I follow it up with `3j`, but change my mind and cancel with `<esc>`. Now, if I repeat the substitution on `map`, only `map`s 3 lines down are highlighted, and the rest are left without highlight:
![bugged](https://user-images.githubusercontent.com/43142209/169859548-c1998fbe-5a23-448b-a2f0-c775dfd0d659.png)

*Great plugin btw :) 
This is a really cool feature that isn't present in `vim-subversive`*

**Comment by gbprod** [comment]
Thanks for the feedback ☺️
I'll check this soon.

I have also noticed this bug for some time, I wonder if it is not related to version 0.7 of neovim.  Which version are you using?

**Comment by gbprod** [comment]
Fixed by #33 
Thanks for the feedback
