### ISSUE TITLE
[Feature Request] Do not save substitutions in call history

### ISSUE THREAD

**Issue by luiz00martins** [gbprod/substitute.nvim#29]
When executing the substitution command, it stays in the `:` call history, together with all other commands. If you make a lot of substitutions, that's quite the problem. All of the (manual) `:` commands that you want to access in the history get drowned by a huge amount of substitution commands that you probably won't want to reuse. 

It would be nice if the substitution command didn't save to the `:` call history.

---

As a suggestion, one possible implementation of this is with the use of `histdel`. The following command performs a substitution, but does not stay on the call history:
```vim
:'[,']s/old_text/new_text/g | call histdel(':', -1)
```

**Comment by gbprod** [comment]
I made something here https://github.com/gbprod/substitute.nvim/pull/31 that can allows you to do that.
I'll merge it soon.
