### ISSUE TITLE
Can we have a shortcut for the substitute-over-range that makes it apply over the whole file?

### ISSUE THREAD

**Issue by IndianBoy42** [gbprod/substitute.nvim#4]
Currently it would be something like `gg<leader>s<motion1>G` or if you had a textobject for 'whole file' it would be `<leader>s<motion1>ie`. which isn't too bad but could be better.

Perhaps, for maximum flexibility add a configuration option that would allow to specify `<motion2>` (the range over which to substitute) from the call in the keymapping. Then we could put `ie`, `ip`, or whatever else might be most common for our workflow.

**Comment by IndianBoy42** [comment]
Btw, thanks for the plugin, I had a very adhoc janky version of the functionality that I wrote myself that I have just replaced with yours because it seems more polished.

**Comment by gbprod** [comment]
Nice idea, I will try to do something soon.

**Comment by gbprod** [comment]
I've tried something [here](https://github.com/gbprod/substitute.nvim/pull/5), can you try this ?

**Comment by IndianBoy42** [comment]
With a quick test it works great, thanks.

The only thing is that because vim doesn't have a 'whole file' textobject the user would have to define that themselves, I don't know if you might want to provide an example of that or provide a separate option for whole file (which could literally just not specify the range in the `:s///` command)

```
map("o", "ie", "<cmd>normal! mzggVG<cr>`z", {noremap=true,silent=true})
```

**Comment by gbprod** [comment]
I don't think that it's the scope of this plugin to provide motions. For my part, I use https://github.com/kana/vim-textobj-entire to do this and I prefer let users map their own motions.

Maybe it could be an option, I will think about it.

For the moment, I think I will just merge this PR and improve this later.

Thanks for this suggestion (and for the support ;) )
