### ISSUE TITLE
Making escape work to cancel exchange action

### ISSUE THREAD

**Issue by asmodeus812** [gbprod/substitute.nvim#40]
Hi, great plugin, a nice replacement for the vim script alternatives. I was wondering if it could be made to respect esc when the exchange is initiated. I.e after the first cx[motion], instead of going off with cxc, to cancel to use . Something similar to how nvim surround works, which is also in a way a two step process (sometimes, depends on the action, but the idea is the same). Or I imagine something like a buffer local variable could be set to allow you to know if you are in the exchange state.

**Comment by gbprod** [comment]
That's a good idea ! I'll try to do something

**Comment by gbprod** [comment]
I've made something here : #43 
Do you want to try before I'll merge ?

**Comment by gbprod** [comment]
Merged !
Thanks :)
