### ISSUE TITLE
How is integration with yanky supposed to be set up?

### ISSUE THREAD

**Issue by bagohart** [gbprod/substitute.nvim#48]
I want the following feature: I want to be able to visually select a word, then press `su`, then `<C-n><C-n> ...` using the yank ring.
If I read the documentation correctly, this is supposed to do the trick:
```lua
        config = function()
            require("substitute").setup({
                on_substitute = function(event)
                    require("yanky").init_ring("p", event.register, event.count, event.vmode:match("[vV�]"))
                end
            })
            -- [...]
            vim.keymap.set("x", "su", "<cmd>lua require('substitute').visual()<cr>")
```
But that doesn't work. What happens is that when pressing `viwsu` the visual selection is correctly replaced, but on pressing `<C-n>`, the original word is restored. Pressing `<C-n>` again does nothing.
Previously, I also had the case that pressing `<C-n>` the second time would restore the original word AND then I could cycle through the yank ring entries directly after the word – but I can't reproduce that now anymore.

However, I do get the desired behaviour by just swapping out the mapping like so:
`vim.keymap.set("x", "su", "<Plug>(YankyPutAfter)")`

What's up with this? Am I reading the doc wrong and this behaviour is intended or is this a bug?

**Comment by gbprod** [comment]
Which version of Neovim are you using ?

Seems that there is a regression on this, I try to find why.

Can you try with : 
```lua
      require("yanky").init_ring("p", event.register, event.count, require("substitute.utils").is_visual(event.vmode))
```

**Comment by bagohart** [comment]
output of `:version`:
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
Trying with that line gives the same result.

**Comment by bagohart** [comment]
Just tested it, seems to work. Nice!

**Comment by gbprod** [comment]
Merged
Thanks for reporting this issue!
