### ISSUE TITLE
Feature Suggestion: Duplication Operator

### ISSUE THREAD

**Issue by chrisgrieser** [gbprod/substitute.nvim#50]
Maybe a bit far-fetched, but I feel like a duplication operator would kinda fit with the spirit of this plugin. Basically, the duplication operator should create a copy of the passed text object. 

A default keybinding that could make sense would be `yd`, since duplication is a form of yanking (and since `gd` is already taken for goto-definition).

`ydiw` would then duplicate a word, `ydd` would duplicate a line, `yD` would duplicate from cursor position to end of line. If the text object covers at least a line, the duplication would copy lines down. If the text object covers less than a line, the duplication would be appended after the text object, but in the same line.

The same way `sip` is basically an equivalent for `vipp`, `ydip` would equivalent to `yipp`.

**Comment by gbprod** [comment]
I really like the idea!
I try to implement this soon :)

**Comment by chrisgrieser** [comment]
there is now [duplicate.nvim](https://github.com/smjonas/duplicate.nvim), which does exactly that, so I guess this request can be withdrawn?
