### ISSUE TITLE
keep cursor at positon before operation

### ISSUE THREAD

**Issue by astier** [gbprod/substitute.nvim#52]
Hi. I switched to this plugin from vim-subversive. So far I am really enjoying it. I especially like the exchange-operator and that I can pass the desired motion to the operation as an option. The only thing I am missing from vim-subversive is the `subversivePreserveCursorPosition` option which keeps the cursor at the position before the operation. For example if I initialize the exchange-operation with `sxiw` the cursor jumps to the beginning of the word. This happens with all operations. Would it be possible to prevent the cursor from changing its position? Thank you.

**Comment by gbprod** [comment]
Yep, I can do something for that!
I'm actually working on a refactoring, I'll work on that after ;)

**Comment by gbprod** [comment]
I've added some options for that  @astier  ;)
