### ISSUE TITLE
Question about integration with `yanky.nvim`

### ISSUE THREAD

**Issue by farzadmf** [gbprod/substitute.nvim#53]
Hi, I recently learned about your plugins and I'm taking them for a test drive

I had a question about the integration:
- In [yank.nvim](https://github.com/gbprod/yanky.nvim/#-integrations), it's mentioned to use this to integrate with `
substitute.nvim`:
```lua
require("substitute").setup({
  on_substitute = require("yanky.integration").substitute(),
})
```
- And in [substitute.nvim](https://github.com/gbprod/substitute.nvim#-integration), it's mentioned to use this to integrate with `yanky.nvim`:
```lua
require("substitute").setup({
  on_substitute = function(event)
    require("yanky").init_ring("p", event.register, event.count, event.vmode:match("[vV�]"))
  end,
})
```

So, I was wondering which one is the correct one 🤔

(also the last character in `...vmode:match("[vV<this-char>]")` appears as a question mark for me when I copy/paste, so I'd appreciate (if that's the one I can use) if you let me know which character it is

Thank you

**Comment by gbprod** [comment]
Hey @farzadmf !
Thanks for giving a try to my plugins, any feedback are welcome.

About the integration, both works but it's betterto use the one from `Yanky` documentation:
```lua
require("substitute").setup({
  on_substitute = require("yanky.integration").substitute(),
})
```

(The last character is the `<c-v>` char, using `yanky.integration` avoid copy/paste problem)

I should update `substitute` readme, thanks for your feedback!

**Comment by gbprod** [comment]
README updated :)

**Comment by farzadmf** [comment]
Hey @gbprod , really appreciate the quick action and sorry for the late reply

Now that I see you're a nice person 😆, can I ask a few questions (they'll probably be stupid because in my [neo]vim years, I haven't used a substitute plugin), so please answer if they make sense and you have the time, and ignore if either is not the case

---

For the integration with `yanky` (I'm enjoying it BTW), what exactly are we trying to achieve? I mean you mention "to enable `yanky` swap when doing substitution", what is the "swap" here that we're enabling?

---

After reading the `README`, I learned about `vim-abolish`, which seems very nice as well, but I was wondering about the "integration" with it (again in the `README`):

  - It's mentioned to set `range.prefix` to `S` to use `vim-abolish` by default, but I'm a bit confused: seems to me that `vim-abolish` is not a replacement for this plugin (I may be wrong, but I think it's basically replacing a word with some variants of it?), so what are we trying to achieve here by this integration?

  - Another thing I'm confused about: what's the effect of setting `range.prefix` to a key (still in the context of `vim-abolish`)? It's mentioned in the `README` that this plugin provides no default mappings, so even if we set `range.prefix` to something, wouldn't it be "overwritten" by what we set in the mappings?

---

Needless to mention again that you have no obligation whatsoever to explain these things to me, but I think this plugins is one of those that will deeply affect my workflow; I feel that's gonna happen, but I haven't yet figured out the full potential

**Comment by gbprod** [comment]
> For the integration with yanky (I'm enjoying it BTW), what exactly are we trying to achieve? I mean you mention "to enable yanky swap when doing substitution", what is the "swap" here that we're enabling?

It means that you can cycle throught [yank-ring](https://github.com/gbprod/yanky.nvim#%EF%B8%8F-yank-ring) after a substitution, this will replace substituted text with previous items of your yank ring (maybe I should be more precise about this in the readme).



> After reading the `README`, I learned about `vim-abolish`, which seems very nice as well, but I was wondering about the "integration" with it (again in the `README`):
> 
>     * It's mentioned to set `range.prefix` to `S` to use `vim-abolish` by default, but I'm a bit confused: seems to me that `vim-abolish` is not a replacement for this plugin (I may be wrong, but I think it's basically replacing a word with some variants of it?), so what are we trying to achieve here by this integration?
> 
>     * Another thing I'm confused about: what's the effect of setting `range.prefix` to a key (still in the context of `vim-abolish`)? It's mentioned in the `README` that this plugin provides no default mappings, so even if we set `range.prefix` to something, wouldn't it be "overwritten" by what we set in the mappings?

[Abolish](https://github.com/tpope/vim-abolish) introduce a new substitution operator that you can use in command line (`Subvert` or just `S`) as you can see in the documentation : https://github.com/tpope/vim-abolish#substitution
(It also exists in [text-case.nvim](https://github.com/johmsalas/text-case.nvim) as `Subs`). This allows to substitute text keeping the same text case. 
When using [substitute over range motion](https://github.com/gbprod/substitute.nvim#-substitute-over-range-motion), it basicly generate a command to substitute text in the selected range motion, `range.prefix` allows to choose the substitution method. 
Eg. By default, this will create a substitution like `:'[,']s/search/replace/g`, but if you set `range.prefix` to `Subvert`, this will create `:'[,']Subvert/search/replace/g` (and use the power of vim-abolish :) )

Is that any clearer to you?

**Comment by lilianchisca** [comment]
@gbprod thank you for answering these mate, had the exact same questions and you explained it perfectly... I think it might be great if these were added in the docs as it's definitely confusing for noobs like me  🙈
