### ISSUE TITLE
Issue with ` key remapped

### ISSUE THREAD

**Issue by ghost** [gbprod/substitute.nvim#55]
Hi there, I noticed `visual()` functions not working properly after I set a custom mapping to ` (backtick key).

I fixed this by using this function instead:

```
function my_visual()
  substitute.state.register = vim.v.register
  substitute.state.count = (vim.v.count > 0 and vim.v.count or 1)
  vim.o.operatorfunc = "v:lua.require'substitute'.operator_callback"
  vim.api.nvim_feedkeys("g@`<", "in", false)
end
```

The only difference is that I appended `"n"` to the `mode` argument of `nvim_feedkeys`.

Do you think this is worth merging for all other users?

(This also makes me wonder, what's the previous mode "i" for? Reading the documentation didn't really help.)

**Comment by gbprod** [comment]
Yes, that make sense, I'll make a fix.

**Comment by gbprod** [comment]
#56 should fix, do you want to try before I merge ?

**Comment by devinalvaro** [comment]
It works, thanks for this and the plugin!
