### ISSUE TITLE
trim when substituting into not-linewise text object

### ISSUE THREAD

**Issue by chrisgrieser** [gbprod/substitute.nvim#60]
Take this example:

```lua
local foo = {
	"apple",
	"orange",
	"banana"
}
buySome(fruits)
```
I yank "banana" with `yy`, go two lines down, and want to substitute "fruits" via `si)`.
```lua
-- result includes the leading whitespace
buySome(	"banana")

-- preferred result
buySome("banana")
```
This issue happens mostly when substituting a linewise register onto a characterwise text obejct. While the plugin is smart enough not to add the trailing line break, it does still insert the leading whitespace, which is slightly annoying. And I cannot think of any scenario where that would be desirable

**Comment by gbprod** [comment]
Hey!
I agree with you, I think we can do better for this use case. I'm thinking about something like the "Special puts" of [yanky](https://github.com/gbprod/yanky.nvim).
I should have time to work on this in the next weeks.

**Comment by gbprod** [comment]
This is not as easy to implements that I thought.
I did not forget about that but it will take longer than expected :sweat_smile:

**Comment by gbprod** [comment]
Hey @chrisgrieser !
Sorry for the late answer :sweat_smile: 

I've almost finished a feature that could interest you here : https://github.com/gbprod/substitute.nvim/pull/66.
I'm interested by some feedback about this if you have some time :)

Thanks

**Comment by gbprod** [comment]
Just merged it :)
But I still interested in your feedback :)

**Comment by chrisgrieser** [comment]
Thanks! I didn't have much time to look into this rn, but from the occasional usage it looks good to me? :)
