### ISSUE TITLE
For substitute.range, is there a way to provide a register or even a lua callback to replace motion1 or motion2?

### ISSUE THREAD

**Issue by IndianBoy42** [gbprod/substitute.nvim#61]
For example the `/` register contains the last search pattern, so being able to use that to replace motion1 in a substitute.range call would be a nice keybinding to have

**Comment by gbprod** [comment]
Interesting idea!

**Comment by schoblaska** [comment]
It'd be great to be able to use visual mode to select the range for `motion2` (often the range I want to replace in can't be described succinctly by a Vim motion). If we were able to set callbacks for motions, that'd probably make it possible!

**Comment by IndianBoy42** [comment]
**Thanos voice** *Fine I'll do it myself*

...and it is done
