### ISSUE TITLE
Error 'start' is higher than 'end'

### ISSUE THREAD

**Issue by pedro757** [gbprod/substitute.nvim#63]
### Error info
```
E5108: Error executing lua ...ite/pack/packer/start/substitute.nvim/lua/substitute.lua:34: 'start' is higher than 'end'                                                                                      
stack traceback:                                                                                                                                                                                             
        [C]: in function 'text'                                                                                                                                                                              
        ...ite/pack/packer/start/substitute.nvim/lua/substitute.lua:34: in function <...ite/pack/packer/start/substitute.nvim/lua/substitute.lua:31>
```

### Steps to reproduce
```rust
struct Monster {
  health: i32,  // With your cursor here copy the content of {} --- yiB or yi{
}

struct Wizard {} // Then here and try to put it inside the {} with your mapping ---- <leader>piB or <leader>pi{ 
```

### Expected behavior
```rust
struct Monster {
  health: i32,
}

struct Wizard {
  health: i32,
}
```

**Comment by gbprod** [comment]
Thanks for reporting this issue. I'll take a look at it ASAP.

**Comment by gbprod** [comment]
I think this issue is fixed by [this commit](https://github.com/gbprod/substitute.nvim/commit/187acf7b45219abbc685e98bc0dc0d1cfbe62813).
Can you tell me if you are using an up-to-date version ?

**Comment by pedro757** [comment]
I'm using the latest version of this plugin.

This is my packer config
```lua
use {
  "gbprod/substitute.nvim",
  config = function()
    require("substitute").setup {}
  end,
}
```

**Comment by gbprod** [comment]
I've made something here : #6
I will test it for a while before merging it.
If you want to try, you're welcome ;)

**Comment by pedro757** [comment]
I tried and got this 

`Substitute failed`

**Comment by gbprod** [comment]
Oh! I forgot a debug log 😂
But does the substitution worked ?

**Comment by pedro757** [comment]
No, It didn't

**Comment by pedro757** [comment]
I believe It's waiting for me to put a register

This is the output when I press `Ctrl-c` after the initial error `Substitute failed`

```
E5108: Error executing lua Keyboard interrupt
stack traceback:
        [C]: in function 'getreg'
        ...ite/pack/packer/start/substitute.nvim/lua/substitute.lua:36: in function <...ite/pack/packer/start/substitute.nvim/lua/substitute.lua:31
```

If I put a register instead of `ctrl-c` then I put the text of the register wrong, like this:

```rust
struct Monster {
  health: i32,  // With your cursor here copy the content of {} --- yiB or yi{
}

  health: i32,struct Wizard {} // Then here and try to put it inside the {} with your mapping ---- <leader>piB or <leader>pi{ 
```

**Comment by gbprod** [comment]
Ok, that's strange, can you share your setup (options for setup method and mapping).

I've made a change to have some logs for debugging purpose, can you try again and tell me what messages you have ?

**Comment by gbprod** [comment]
Any feedback on this issue @pedro757 ?
It seems to work for me.

**Comment by pedro757** [comment]
I just tried the new branch #64 it works fine, however I'm also using wellle/targets.vim, but these plugins are incompatible right now.

**Comment by gbprod** [comment]
Can you open a issue explaining the compatibilities issues you have with wellle/targets.vim ?
Thanks
