### ISSUE TITLE
[substitute.range] Replace occurence with register in ... <some motion>

### ISSUE THREAD

**Issue by keevan** [gbprod/substitute.nvim#68]
Hello! Great plugin. I'm a former Atom user of vim mode plus and I'm trying to set this up similarly to the occurrence modifier, and it's working mostly good.

With `substitute.range`, Is there a way to specify a subject.motion, the register, and have it execute the replace without needing to press enter to confirm the command? 

What I'm actually doing is:
- yank some text (e.g. a word), 
- move cursor to top of word in function to replace,
- trigger the following `require("substitute.range").operator({ subject = { motion = "iw" }, register = "0" })`
- do the motions to indicate range (e.g. function motion would be `if`)
- press enter to confirm replacement (because I've already set it to the register, I'm hoping to eliminate this perhaps with another configuration option)

**Comment by keevan** [comment]
For other wandering ex-Atom users, the relevant keymaps I use mostly are:
```
-- Replace occurence with value in clipboard
vim.keymap.set("n", "-o", function()
	require("substitute.range").operator({ subject = { motion = "iw" }, register = "0" })
end, { noremap = true })

-- Change occurence
vim.keymap.set("n", "co", function()
	require("substitute.range").operator({ subject = { motion = "iw" } })
end, { noremap = true })
```

**Comment by gbprod** [comment]
Hey, that's a great idea of enhancement.
I'm thinking of something like this : 

	require("substitute.range").operator({ subject = { motion = "iw" }, register = "0", auto_apply = true })

What do you think about that ?

**Comment by keevan** [comment]
Option sounds good and self explanatory. Probably only needs docs to let users know it depends on a few things being set to work as intended.

Thanks for looking into it :)

**Comment by gbprod** [comment]
Done. 😉
Let me know if it is ok for you
