### ISSUE TITLE
[substitute.range] Quickly prefix text

### ISSUE THREAD

**Issue by keevan** [gbprod/substitute.nvim#69]
Hi there! I've managed to add the behaviour I want for adding text to a current selection.

```lua
-- Mark word visually, then edit all occurences based on range / motion.
vim.keymap.set("x", "mA", function()
	require("substitute.range").visual({ prompt_current_text = true })
end, { noremap = true })
```

But there doesn't appear to be an easy way to start editing from the start of the current text. I find myself press the arrow keys to go to the start of the word, and it's worse the longer the current_text is, `ctrl+left arrow` seems to jump to the start of the command which isn't ideal either, and `alt+left arrow` doesn't work

I understand it's a bit of a hack to want to prefix things this way. Hopefully it's a small change.

**Comment by gbprod** [comment]
hmm, I think I can do something for that, I will keep you informed

**Comment by bew** [comment]
I'm thinking it would be nice to place the cmdline cursor at the same position of the cursor when the plugin is invoked.

(given `|` represents the cursor)
So if line is `foo|barbaz`
Cmdline would be: `s/foobarbaz/foo|barbaz/g` (for example)

Edge case when cursor is not in `motion1`, but then that behavior can simply be disabled

**Comment by gbprod** [comment]
Interesting, I probably add an option to select that.
I'll try to implement this soon but if you are in a hurry, the best is to open a PR ;)
