### ISSUE TITLE
Highlighting the subject works only when cursor position is at the start of the subject

### ISSUE THREAD

**Issue by keevan** [gbprod/substitute.nvim#70]
Hello! I noticed a visual bug / inconsistency and I'm not sure if it's just me.

When I run `require("substitute.range").operator()`, and do `w` (word motion), it shows the highlights for matching occurrences as expected.

![image](https://github.com/gbprod/substitute.nvim/assets/9924643/7a5691f7-c704-4e47-98e1-2d2c71bd05b0)
(Example with a subword motion)

However when doing inner word (or in my case inner subword), no highlighting is displayed for the subject, not even the first, when I start from somewhere in the middle:

![image](https://github.com/gbprod/substitute.nvim/assets/9924643/1a93d352-4d7c-4ec1-b03c-64a4ce279ee3)

It does however shift the cursor to the start of the subject (which is fine) though it would be nice to get visual feedback before doing the motion to replace.

Proceeding with the motion shows the command mode text and the rest works fine, so it's functionally OK.

![image](https://github.com/gbprod/substitute.nvim/assets/9924643/b863ae66-5109-420f-a2f4-e8edd643fc59)

**Comment by gbprod** [comment]
Interesting issue, I'll try to fix it soon

**Comment by gbprod** [comment]
Fixed!
Thanks
