### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by emilBeBri** [gbprod/substitute.nvim#80]
Hi so the last week or so, when I use the operator it does substitute the word, but I also get this error: 

```
E5108: Error executing lua ...local/share/nvim/lazy/substitute.nvim/lua/substitute.lua:45: attempt to index field 'highlight_substituted_text' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/substitute.nvim/lua/substitute.lua:45: in function <...local/share/nvim/lazy/substitute.nvim/lua/substitute.lua:31>
```

Tried updating all plugins, reinstalling substitute.nvim, it still does it, with all these (default mapping) motions:

```

vim.keymap.set("n", "s", require('substitute').operator, { noremap = true })
vim.keymap.set("n", "ss", require('substitute').line, { noremap = true })
vim.keymap.set("n", "S", require('substitute').eol, { noremap = true })
vim.keymap.set("x", "s", require('substitute').visual, { noremap = true })

```

on Endavour Linux, fully updated and NVIM: 

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921

   system vimrc file: "$VIM/sysinit.vim"
     fall-back for $VIM: "/usr/share/nvim"
```

Best,

**Comment by gbprod** [comment]
Do you call `require('substitute').setup({})` before using it ?

**Comment by emilBeBri** [comment]
That did it:

return{

-- other plugins loaded here

    { 'gbprod/substitute.nvim', config = function()  
        require('substitute').setup {}
    end
    },

-- other plugins loaded here

}
 thank you - strange though, because I've been using your plugin (w. lazy) for at least 10 months and it's only last week that this became an issue.
