### ISSUE TITLE
Does not seem to work with TOML

### ISSUE THREAD

**Issue by djmango** [gbprod/substitute.nvim#88]
Substitute does not seem to work in TOML files for some reason. Attempting to use with my gr keybind seems to just trigger standard "r" replace function, replacing a single character with "i" for example when I do "grib", replace with register in brackets.

I'm using LunarVim with substitute, configured to gr this way:

`lvim.lsp.buffer_mappings.normal_mode["gr"] = { require("substitute").operator, "Substitute with register" }`

works in other files no problem, json, swift, rust, etc

**Comment by gbprod** [comment]
Hi!
I'm not familiar with LunarVim but it seems that the mapping `lvim.lsp.buffer_mappings` seems to apply on buffers with LSP server attached, and I don't think there is any LSP server for toml.

Maybe your should try with something like : 

```lua
lvim.keys.normal_mode["gr"] = { require("substitute").operator, "Substitute with register" }
```

**Comment by djmango** [comment]
Oh good catch! missed that - for future reference this is the config that worked

```lua
lvim.keys.normal_mode["gr"] = ":lua require('substitute').operator()<CR>"
```
